from .alergia_service import Alergiaservice
from .consentimento_service import Consentimentoservice
from .doenca_cronica_service import DoencaCronicaservice
from .medicamento_em_uso_service import MedicamentoEmUsoservice
from .obs_tipo_sanguineo_service import ObservacaoTipoSanguineoservice
from .reacao_alergia_service import ReacaoAlergiaservice
from .paciente_service import Pacienteservice